fix: missing head ref (#310)
以下に対応するための変更を加えます

- detached HEAD になっている
- push時プッシュ先refが分からない

```
Run git -c "user.name=github-actions[bot]" -c "user.email=github-actions[bot]@users.noreply.github.com" commit -a -m "ci: format"
[detached HEAD ce67b1d] ci: format
 195 files changed, 1424 insertions(+), 1023 deletions(-)
error: The destination you provided is not a full refname (i.e.,
starting with "refs/"). We tried to guess what you meant by:

- Looking for a ref that matches 'HEAD' on the remote side.
- Checking if the <src> being pushed ('HEAD')
  is a ref in "refs/{heads,tags}/". If so we add a corresponding
  refs/{heads,tags}/ prefix on the remote side.

Neither worked, so we gave up. You must fully qualify the ref.
hint: The <src> part of the refspec is a commit object.
hint: Did you mean to create a new branch by pushing to
hint: 'HEAD:refs/heads/HEAD'?
error: failed to push some refs to 'https://github.com/tuqulore/vue-3-practices'
```

_https://github.com/tuqulore/vue-3-practices/actions/runs/7088795558/job/19292068971 より_